# Zmienne i struktury danych

## Zmienna liczbowa

In [1]:
i = 5
i

5

In [2]:
i = 5 - 2
i

3

## Ciąg znaków (string)

In [3]:
s = 'napis'
s

'napis'

In [4]:
'na' + 'pis'  # string concatenation

'napis'

## Zmienne logiczne

In [5]:
b = True
b

True

In [6]:
if b:
    print('true!')
else:
    print('false!')

true!


In [7]:
bs = 'true!' if b else 'false!'
bs

'true!'

## Wartość None

In [8]:
n = None
n

In [9]:
print(n)

None


In [10]:
n is None

True

In [11]:
n

In [12]:
n is None

True

## Lista

In [6]:
l = [1, 2, 4, 8.4]
l

[1, 2, 4, 8.4]

In [12]:
l.append(12)
l.size

AttributeError: 'list' object has no attribute 'size'

In [11]:
l[1:-1]  # weź elementy do przedostatniego

[2, 4, 8.4, 12, 12, 12]

In [16]:
l[1:-1:2]  # od pierwszego elementu do przedostatniego co drugi element

[2, 8.4]

In [17]:
l[::2]  # co drugi element

[1, 4, 12]

## Słownik

In [18]:
d = {1: 'jeden', 2: 'dwa', 'trzy': 3}

In [19]:
d[100] = 'sto'
d

{1: 'jeden', 2: 'dwa', 'trzy': 3, 100: 'sto'}

In [20]:
d['trzy']

3

## Krotka

In [21]:
t = [4, 2, 5], 'slowo', 4.6
t

([4, 2, 5], 'slowo', 4.6)

In [22]:
t[0]

[4, 2, 5]

In [23]:
l, s, _ = t
s

'slowo'

## Macierze (w NumPy)

In [3]:
import numpy as np

In [4]:
A = np.array([[5], [3]])
A

array([[5],
       [3]])

In [5]:
B = np.array([[1, 2], [3, 4]])
B

array([[1, 2],
       [3, 4]])

In [6]:
C = np.array([[1.25, 0.5], [16.75, 20.1]])
C

array([[ 1.25,  0.5 ],
       [16.75, 20.1 ]])

# Podstawowe operacje

## Operacje logiczne

In [7]:
C = np.array([[0, 1], [1, 1]])
C
lista1 = [1,2,3,4,5]
lista2 = [6,7,8,9,10]
matrix = np.array([lista1, lista2])
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
D = C.astype(bool)
D

array([[False,  True],
       [ True,  True]])

In [9]:
E = np.array([[True, True], [False, True]])
E

array([[ True,  True],
       [False,  True]])

In [10]:
D

array([[False,  True],
       [ True,  True]])

In [11]:
~D

array([[ True, False],
       [False, False]])

In [12]:
E

array([[ True,  True],
       [False,  True]])

In [13]:
D & E

array([[False,  True],
       [False,  True]])

In [14]:
D | E

array([[ True,  True],
       [ True,  True]])

## Dodawanie

In [23]:
print(B)
B + 100.5


[[1 2]
 [3 4]]


array([[101.5, 102.5],
       [103.5, 104.5]])

In [16]:
C

array([[0, 1],
       [1, 1]])

In [17]:
B + C

array([[1, 3],
       [4, 5]])

## Mnożenie macierzowe

In [18]:
B @ C

array([[2, 3],
       [4, 7]])

In [40]:
B.dot(C)

array([[2, 3],
       [4, 7]])

In [41]:
B @ A

array([[11],
       [27]])

In [42]:
result = A.transpose() @ B
result

array([[14, 22]])

## Iloczyn Hadamarda

In [43]:
B

array([[1, 2],
       [3, 4]])

In [44]:
C

array([[0, 1],
       [1, 1]])

In [45]:
result = B * C
result

array([[0, 2],
       [3, 4]])

## Podnoszenie elementów do potęgi

In [46]:
B

array([[1, 2],
       [3, 4]])

In [47]:
result = B**2
result

array([[ 1,  4],
       [ 9, 16]])

## Odwołania do elementów

In [48]:
B

array([[1, 2],
       [3, 4]])

In [49]:
B[0, 1]

2

In [50]:
B[1, :]

array([3, 4])

In [51]:
B[:, 0]

array([1, 3])

In [52]:
B

array([[1, 2],
       [3, 4]])

In [53]:
B[1]

array([3, 4])

In [54]:
B[:-1]

array([[1, 2]])

## Konkatenacja

In [55]:
B

array([[1, 2],
       [3, 4]])

In [56]:
C

array([[0, 1],
       [1, 1]])

In [57]:
D = np.concatenate([B, C])
D

array([[1, 2],
       [3, 4],
       [0, 1],
       [1, 1]])

In [58]:
D = np.concatenate([B, C], axis=1)
D

array([[1, 2, 0, 1],
       [3, 4, 1, 1]])

# Podstawowe funkcje

In [59]:
A

array([[5],
       [3]])

In [60]:
np.sin(A)

array([[-0.95892427],
       [ 0.14112001]])

In [61]:
np.cos(A)

array([[ 0.28366219],
       [-0.9899925 ]])

In [62]:
np.exp(A)

array([[148.4131591 ],
       [ 20.08553692]])

In [63]:
np.log(A)

array([[1.60943791],
       [1.09861229]])

In [64]:
np.sqrt(A)

array([[2.23606798],
       [1.73205081]])

In [65]:
np.abs(A)

array([[5],
       [3]])

In [66]:
B

array([[1, 2],
       [3, 4]])

In [67]:
np.sum(B)

10

In [68]:
np.sum(B, axis=0)

array([4, 6])

In [69]:
np.sum(B, axis=1)

array([3, 7])

In [70]:
np.sum(B, axis=1, keepdims=True)

array([[3],
       [7]])

In [71]:
B

array([[1, 2],
       [3, 4]])

In [72]:
np.prod(B)

24

In [73]:
np.prod(B, axis=0)

array([3, 8])

In [74]:
np.prod(B, axis=1)

array([ 2, 12])

In [75]:
np.prod(B, axis=1, keepdims=True)

array([[ 2],
       [12]])

In [128]:
np.max(B)

4

In [77]:
A

array([[5],
       [3]])

In [78]:
np.linalg.norm(A)

5.830951894845301

In [79]:
np.sqrt(np.sum(A**2))

5.830951894845301

In [80]:
B

array([[1, 2],
       [3, 4]])

In [81]:
np.trace(B)

5

In [82]:
np.linalg.inv(B)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [83]:
np.linalg.inv(B) @ B

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

## Stałe

In [84]:
np.inf

inf

In [85]:
np.nan

nan

In [86]:
np.pi

3.141592653589793

In [87]:
np.e

2.718281828459045

## Sortowanie

In [129]:
G = np.array([6, 4, 5])
G

array([6, 4, 5])

In [130]:
np.sort(G)

array([4, 5, 6])

In [136]:
G[np.argsort(G)]

array([4, 5, 6])

In [131]:
np.argsort(G)

array([1, 2, 0])

# Wymiary

In [91]:
B

array([[1, 2],
       [3, 4]])

In [92]:
B.shape

(2, 2)

In [93]:
B.shape[0]

2

In [94]:
B

array([[1, 2],
       [3, 4]])

In [95]:
np.reshape(B, (4, 1))

array([[1],
       [2],
       [3],
       [4]])

In [140]:
np.reshape(B, (-1, 4))

array([[1, 2, 3, 4]])

In [97]:
np.reshape(B, (-1))

array([1, 2, 3, 4])

In [98]:
B

array([[1, 2],
       [3, 4]])

In [99]:
B.shape

(2, 2)

In [100]:
BB = np.expand_dims(B, axis=1)
BB.shape

(2, 1, 2)

In [101]:
BB.squeeze().shape

(2, 2)

# Deklaracja różnych macierzy

In [102]:
np.zeros(shape=(3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [103]:
np.ones(shape=(3, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [104]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [105]:
np.random.rand(3, 2)

array([[0.80300869, 0.02175586],
       [0.26945335, 0.49418857],
       [0.37029408, 0.82813343]])

In [106]:
np.random.randn(3, 2)

array([[-2.08464931, -0.12924815],
       [ 0.6156818 ,  1.99161572],
       [ 2.35813699,  0.11534061]])

In [107]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
np.arange(5, 12)

array([ 5,  6,  7,  8,  9, 10, 11])

In [109]:
np.arange(5, 12, 2)

array([ 5,  7,  9, 11])

# Funkcje

In [110]:
def say_hi(s):
    print(f'hi, {s}!')
    print('hi, ' + s + '!')
    
say_hi('hello')

hi, hello!
hi, hello!


In [111]:
A = np.array([1, 3, 5, 11])

def sum_squared(x):
    ss = 0
    for i in range(x.shape[0]):
        ss += x[i] ** 2
    return ss

sum_squared(A)

156

In [112]:
def sum_squared(x):
    suma = 0
    for i in x:
        suma += i ** 2
    return suma

sum_squared(A)

156

In [113]:
def is_even(x):
    return x % 2 == 0

is_even(12)

True

In [114]:
def is_sum_squared_even(x):
    ss = sum_squared(x)
    e = is_even(ss)
    return ss, e

is_sum_squared_even(A)

(156, True)

In [36]:
m1 = np.array([[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1]])
m1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [37]:
m2 = np.eye(3)
m2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
m1+m2

ValueError: operands could not be broadcast together with shapes (6,3) (3,3) 

In [40]:
for i in [4,5]:
    print(i)

4
5


In [47]:
t = (1,2)
t += 3,2,2,2,2
t

(1, 2, 3, 2, 2, 2, 2)

In [48]:
t = 1,1
t

(1, 1)

In [61]:
t = 1,1
t = t + (2,) + (3,)
t[2]

2